name: myride
description: A ride-booking app like Uber
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.0
  firebase_database: ^10.4.0
  google_maps_flutter: ^2.6.0
  location: ^5.0.0
  provider: ^6.1.0
  flutter_polyline_points: ^2.0.0
  geocoding: ^2.1.0

flutter:
  uses-material-design: true
